security:
    # encoders:
    #     TuanQuynh\RestBundle\Entity\AdminUser:
    #         algorithm: sha512
    #         encode-as-base64: true
    #         iterations: 10

    # providers:
    #     main:
    #         entity:
    #             class: TuanQuynh\RestBundle\Entity\AdminUser
    #             property: email

    firewalls:
        # dev:
        #     pattern:  ^/api/(_(profiler|wdt|doc))/
        #     security: false

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path: /api/login_check
                require_previous_session: false
                username_parameter: email
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:
                    enabled: true
                    name:    bearer


    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
